framework:
    html_sanitizer:
        sanitizers:
            app.hard:
                allow_safe_elements: false
                allow_static_elements: false
            app.chapter_content:
                allow_safe_elements: true
                allow_elements:
                    h1: '*'
                    h2: '*'
                    h3: '*'
                    ul: '*'
                    ol: '*'
                    li: '*'
                    strong: '*'
                    em: '*'
                    b: '*'
                    i: '*'
                    p: '*'
                    br: '*'
